---
- name: Installation de K3s sur le Master
  shell: curl -sfL https://get.k3s.io | sh -
  args:
    creates: /usr/local/bin/k3s
  when: inventory_hostname == groups['kubernetes'][0]

- name: Attente du démarrage de K3s
  wait_for:
    path: /var/lib/rancher/k3s/server/node-token
    state: present
  when: inventory_hostname == groups['kubernetes'][0]

- name: Lecture du Token K3s
  slurp:
    src: /var/lib/rancher/k3s/server/node-token
  register: k3s_token_base64
  when: inventory_hostname == groups['kubernetes'][0]

- name: Définition du Token en variable globale (Fact)
  set_fact:
    k3s_token: "{{ k3s_token_base64['content'] | b64decode | trim }}"
    k3s_master_ip: "{{ groups['kubernetes'][0] }}" 
  when: inventory_hostname == groups['kubernetes'][0]
  delegate_to: "{{ item }}"
  delegate_facts: true
  with_items: "{{ groups['kubernetes'] }}"

- name: Installation de K3s sur les Workers (Join Cluster)
  shell: "curl -sfL https://get.k3s.io | K3S_URL=https://{{ k3s_master_ip }}:6443 K3S_TOKEN={{ k3s_token }} sh -"
  args:
    creates: /usr/local/bin/k3s
  when: inventory_hostname != groups['kubernetes'][0]